// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	domain "go-template/domain"

	mock "github.com/stretchr/testify/mock"
)

// FarmUsecase is an autogenerated mock type for the FarmUsecase type
type FarmUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: input
func (_m *FarmUsecase) Create(input domain.CreateFarmDto) (uint, error) {
	ret := _m.Called(input)

	var r0 uint
	if rf, ok := ret.Get(0).(func(domain.CreateFarmDto) uint); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(uint)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.CreateFarmDto) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *FarmUsecase) Delete(id uint) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *FarmUsecase) GetAll() ([]domain.Farm, error) {
	ret := _m.Called()

	var r0 []domain.Farm
	if rf, ok := ret.Get(0).(func() []domain.Farm); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Farm)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: id
func (_m *FarmUsecase) GetById(id uint) (domain.Farm, error) {
	ret := _m.Called(id)

	var r0 domain.Farm
	if rf, ok := ret.Get(0).(func(uint) domain.Farm); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.Farm)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: input
func (_m *FarmUsecase) Update(input domain.UpdateFarmDto) error {
	ret := _m.Called(input)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.UpdateFarmDto) error); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
